//
// Copyright 2016 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
//
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to 
// copy, distribute and modify it.
//
// Source code generated from template: aws-my-sample-app-android v0.10
//
package com.amazonaws.mobile;

import com.amazonaws.regions.Regions;

/**
 * This class defines constants for the developer's resource
 * identifiers and API keys. This configuration should not
 * be shared or posted to any public source code repository.
 */
public class AWSConfiguration {

    // AWS MobileHub user agent string
    public static final String AWS_MOBILEHUB_USER_AGENT =
        "MobileHub 10b6c6e7-c8bc-43dc-92b2-c1fbea01a139 aws-my-sample-app-android-v0.10";
    // AMAZON COGNITO
    public static final Regions AMAZON_COGNITO_REGION =
      Regions.fromName("us-east-1");
    public static final String  AMAZON_COGNITO_IDENTITY_POOL_ID =
        "us-east-1:9a973db3-0855-4b34-85b7-b4dbed135f34";
    public static final String AMAZON_COGNITO_USER_POOL_ID =
        "us-east-1_SOKssP1WD";
    public static final String AMAZON_COGNITO_USER_POOL_CLIENT_ID =
        "1cu7qq9nc0dte5bfkuk4ru8vjk";
    public static final String AMAZON_COGNITO_USER_POOL_CLIENT_SECRET =
        "1cu085tb41dedsmglrrqeu6mcq0l8ptt26h4omnc8m303rrr265n";
}
